# this is a basic project that does not use an LLM to generate any text;
# it is useful for debugging / testing purposes because it:
# 1. ensures deterministic results
# 2. does not result in API charges

"$PROJECT/outline.json":
  cmd: cp $PROJECT/basic.json $PROJECT/outline.json && sleep 0.5
  dependencies: |
    $PROJECT/basic.json
    $PROJECT/deps/a
    $PROJECT/deps/b

"$PROJECT/sub$LEVEL1/outline.json":
  cmd: |
    cp $PROJECT/basic.json $PROJECT/sub$LEVEL1/outline.json && sleep 0.5
  dependencies: |
    $PROJECT/outline.json
  variables:
    LEVEL1: |
      jq -r 'range(0; .sections | length)' $PROJECT/outline.json | tr '\n' '\0'

"$PROJECT/sub$LEVEL1/sub$LEVEL2/outline.json":
  cmd: |
    cp $PROJECT/basic.json $PROJECT/sub$LEVEL1/sub$LEVEL2/outline.json && sleep 0.5
  dependencies: |
    $PROJECT/outline.json
  variables:
    LEVEL1: |
      jq -r 'range(0; .sections | length)' $PROJECT/outline.json | tr '\n' '\0'
    LEVEL2: |
      jq -r 'range(0; .sections | length)' $PROJECT/sub$LEVEL1/outline.json | tr '\n' '\0'

"$PROJECT/final.txt":
  cmd: |
    touch "$PROJECT/final.txt" && sleep 0.5
  dependencies: |
    $PROJECT/sub$LEVEL1/sub$LEVEL2/outline.json
